server:
  port: 8080
spring:
  application:
    name: metrics-test
management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
          - metrics
          - prometheus
  endpoint:
    health:
      show-details: ALWAYS